### PR TITLE
Enable parallel uploads and fix async. Assemblies

### LINKED ISSUE #20: Allow parallel uploads
currently, assembly uploads of multiple files are done sequentially. It'd be nice if this can be done in parallel to speed up the Assembly processing.

### LINKED ISSUE #69: Use of UploadProgressListener causes exception
The use of the UploadProgressListener of the Async Assemblies causes an NullPointerException as the AssemblyRunnable calls ```getListener().onAssemblyFinished(watchStatus());``` . 
If you use the UploadProgressListener there is no AssemblyProgressListener instance that can be returned by ```getListener()```.  In this case, you are facing a NullPointerException every time the assembly processing is finished.

This behavior is also reproducible with the examples provided by the SDK.

### PR DESCRIPTION
**Pull request by cdr-chakotay**
The aim of this PR is to add full parallel upload support to the Java SDK for both synchronous and asynchronous assemblies.

Archivement Checklist:
- [x] Make synchronous Assemblies uploadable in parallel
- [x] Make the number of Uploadthreads adjustable
- [x] Discuss default settings for the number of upload threads (currently 2)
- [x] ~~Make asynchronous Assemblies uploadable in parallel~~ => everything is possible without extra Async Assembly
- [x] Make all the changes jUnit testable (open for recommendations)
- [x] Make Error reporting better
closes #20 

Optionals:
- ~~Fix AsyncAssemblyListener bug~~ => will not be part of this PR
- [x] Fix Nullpointer exception bug in async assemblies closes #69

### CODE REVIEW

File: src/main/java/com/transloadit/sdk/TusUploadThread.java [hunk 1]
```diff
@@ -0,0 +1,71 @@
...
+import io.tus.java.client.TusUploader;
+
+import java.io.IOException;
+import java.time.LocalDateTime;
+import java.time.format.DateTimeFormatter;
+
+/**
+ * This class provides a TusUpload as Thread in order to enable parallel Uploads.
+ */
+public class TusUploadThread extends Thread {
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/TusUploadThread.java:15]: Can we make this class package private? I don't think there is a reason for outsiders to interact directly with it, or is there?

File: src/main/java/com/transloadit/sdk/TusUploadThread.java [hunk 2]
```diff
@@ -0,0 +1,71 @@
...
+        try {
+            // todo: remove the timestamp debug code
+            DateTimeFormatter fmt = DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss.SSS");
+            LocalDateTime localDateTime = LocalDateTime.now();
+            String format = fmt.format(localDateTime);
+            System.out.println("Uploadstarted: " +  " Name: " + this.getName() + " Timestamp: " + format);
+
+            tusExecutor.makeAttempts();
+        } catch (ProtocolException e) {
+            e.printStackTrace();
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/TusUploadThread.java:46]: I think we need a proper way to bubble up errors here, right?

**Review by Acconut — COMMENTED** [review]
Wow, that is very elegant approach! Let me know if this is ready for a proper review once all the TODOs are addressed.

File: src/main/java/com/transloadit/sdk/TusUploadThread.java (hunk 1 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/TusUploadThread.java:15]: Yes of course we can, i will add this to my Todos :)

File: src/main/java/com/transloadit/sdk/TusUploadThread.java (hunk 2 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/TusUploadThread.java:46]: Yes, definitively. This is one of the topics i have to talk about with you :)

**Comment by cdr-chakotay** [comment]
> Wow, that is very elegant approach! Let me know if this is ready for a proper review once all the TODOs are addressed.

Thank you very much!

I think it is also possible to provide the pause/play functionality of the Async Assembly within this class. 
I have already a promising sketch running. 

I'll let you know as soon as I am ready for a review!

**Comment by cdr-chakotay** [comment]
@Acconut tweaked error reporting a little bit. 
I am using the async upload progress listener now to inform the user about broken uploads. Should I add a default configuration, which reports always if something happens ?

Or what kind of thoughts do you have? Open for change requests ;)

**Comment by Acconut** [comment]
What is the state of this PR? Were you waiting on some more input? :)

**Comment by cdr-chakotay** [comment]
Honestly postponed it, because all the Gradle and Maven stuff was more urgent. Will continue here, when I am back :)

**Comment by Acconut** [comment]
Ok, sounds good! Thanks for the feedback!

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java [hunk 3]
```diff
@@ -124,19 +123,62 @@ public void onAssemblyResultFinished(String stepName, JSONObject result) {
                 System.out.println("\n ---- Step Result for Step: ---- ");
                 System.out.println("StepName: " + stepName + "\nFile: " + result.get("basename") + "."
                         + result.get("ext"));
-                System.out.println("Downlaodlink: " + result.getString("ssl_url") + "\n");
+                System.out.println("Downloadlink: " + result.getString("ssl_url") + "\n");
```
Comment (Acconut) [inline examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:126]: Let's add a space: `Download link:`

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java [hunk 4]
```diff
@@ -124,19 +123,62 @@ public void onAssemblyResultFinished(String stepName, JSONObject result) {
...
+            UploadProgressListener uploadProgressListener = new UploadProgressListener() {
+                @Override
+                public void onUploadFinished() {
+                    System.out.println("All file uploads have been finished.");
+
+                }
 
+                @Override
+                public void onUploadProgress(long uploadedBytes, long totalBytes) {
+                   // System.out.println("Upload: " + uploadedBytes + " from: " + totalBytes);
```
Comment (Acconut) [inline examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:140]: It this intended to be commented out?

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java [hunk 5]
```diff
@@ -124,19 +123,62 @@ public void onAssemblyResultFinished(String stepName, JSONObject result) {
...
+                }
+
+                @Override
+                public void onParallelUploadsResumed(String name) {
+                    System.out.println("Resumed: " + name);
+
+                }
+            };
+            assembly.setUploadProgressListener(uploadProgressListener);
+            assembly.setMaxParallelUploads(2); // todo: backward Compability
```
Comment (Acconut) [inline examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:167]: Is this TODO still relevant?

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java [hunk 6]
```diff
@@ -124,19 +123,62 @@ public void onAssemblyResultFinished(String stepName, JSONObject result) {
...
+            assembly.setUploadChunkSize(50);
             assembly.save(true);
-         } catch (LocalOperationException | RequestException e) {
+
+            Thread.sleep(50);  // todo: adjust for new modules
```
Comment (Acconut) [inline examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:171]: Is this TODO still relevant?

File: src/main/java/com/transloadit/sdk/Assembly.java [hunk 7]
```diff
@@ -193,7 +211,7 @@ private String normalizeDuplicateName(String name) {
      *
      * @return the number of files that have been added for upload.
      */
-    public int getFilesCount() {
+    public int getNumberOfFiles() {
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/Assembly.java:214]: Did you rename this method to better suite its purpose? It is a breaking chance, which we need to release in a new major version. No big issue, just want to confirm with you.

File: src/main/java/com/transloadit/sdk/Assembly.java [hunk 8]
```diff
@@ -383,31 +402,73 @@ protected TusUpload getTusUploadInstance(File file) throws FileNotFoundException
...
+     * @throws IOException Input Streams cannote be read
+     */
+    public long getUploadSize() throws IOException {
+        long totalUploadSize = 0;
+        for (Map.Entry<String, File> entry : files.entrySet()) {
+            totalUploadSize += entry.getValue().length();
+        }
+
+        for (Map.Entry<String, InputStream> entry : fileStreams.entrySet()) {
+            totalUploadSize += entry.getValue().available();
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/Assembly.java:417]: We need to be cautious. `available()` does not always return the full number of bytes. See the docs https://docs.oracle.com/javase/7/docs/api/java/io/InputStream.html#available()

> Note that while some implementations of InputStream will return the total number of bytes in the stream, many will not

If I see correctly, we are using the total upload size to check whether `onUploadFinish` should be called. Instead of checking the upload progress if all data has been transferred, the finish callback should only be invoked if the tus server responded that the upload was complete (i.e. tus-java-client finishes the upload). Does that make sense?

File: src/main/java/com/transloadit/sdk/TusUploadRunnable.java [hunk 9]
```diff
@@ -0,0 +1,173 @@
...
+                        }
+
+                        if (!isPaused) {
+                            isRunning = true;
+                            uploadedChunk = tusUploader.uploadChunk();
+                            if (uploadedChunk > -1) {
+                                assembly.updateUploadProgress(uploadedChunk);
+                            }
+                        } else {
+                            if (isStarted) {
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/TusUploadRunnable.java:106]: Can you explain the check for isStarted here? The entire pause logic confuses me a bit.

File: src/main/java/com/transloadit/sdk/async/AssemblyProgressListener.java [hunk 10]
```diff
@@ -2,10 +2,12 @@
 
 import com.transloadit.sdk.response.AssemblyResponse;
 
+
 /**
  * Implementations of this interface are used to handle progress and completion of a background
  * Assembly file upload and execution.
  */
+@Deprecated
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/async/AssemblyProgressListener.java:10]: Please add the proper documentation to the JavaDoc to explain the deprecation and point to the alternative.

File: src/main/java/com/transloadit/sdk/async/AsyncAssembly.java [hunk 11]
```diff
@@ -18,17 +18,19 @@
 import java.util.concurrent.Executors;
 import java.util.concurrent.TimeUnit;
 
+
 /**
  * This class represents a new assembly being created.
  * It is similar to {@link Assembly} but provides Asynchronous functionality.
  */
+@Deprecated
```
Comment (Acconut) [inline src/main/java/com/transloadit/sdk/async/AsyncAssembly.java:26]: Please add the proper documentation to the JavaDoc to explain the deprecation and point to the alternative. Why are we deprecating this class?

**Review by Acconut — COMMENTED** [review]
Wow, a lot of work went into this! Thanks!

File: src/main/java/com/transloadit/sdk/async/AsyncAssembly.java (hunk 11 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/async/AsyncAssembly.java:26]: Because our new multithreaded uploads are able to handle all the things, this class could handle. And also in a cleaner way with the TUS changes we did :)

File: src/main/java/com/transloadit/sdk/async/AssemblyProgressListener.java (hunk 10 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/async/AssemblyProgressListener.java:10]: Will do

File: src/main/java/com/transloadit/sdk/async/UploadProgressListener.java [hunk 12]
```diff
@@ -25,4 +25,23 @@ public interface UploadProgressListener {
...
+     * Callback to be executed if an already running, parallel upload gets paused.
+     * @param name Name of the upload Thread, which gets paused.
+     */
+    void onParallelUploadsPaused(String name);
+
+    /**
+     * Callback to be executed if an already running, parallel upload gets paused.
+     * @param name Name of the upload Thread, which gets paused.
+     */
+    void onParallelUploadsResumed(String name);
```
[the remark this answers is not in the document]
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/async/UploadProgressListener.java:46]: I did those to have the user informed when uploads are pausing or resumed. I thought it makes it easier for UI building with an app if you want to have a status bar. Or a Play Pause Button. What do you think ?

File: .github/linters/sun_checks.xml [hunk 13]
```diff
@@ -137,7 +137,9 @@
 
     <!-- Checks for Size Violations.                    -->
     <!-- See https://checkstyle.org/config_sizes.html -->
-    <module name="MethodLength"/>
```
[the remark this answers is not in the document]
Comment (cdr-chakotay) [reply .github/linters/sun_checks.xml:140]: I think I removed it because it was so nasty for both of us, as it broke links in the docs and so on. I will double check :)

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java (hunk 5 above)
Comment (cdr-chakotay) [reply examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:167]: No :)

File: src/main/java/com/transloadit/sdk/async/AsyncAssembly.java (hunk 11 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/async/AsyncAssembly.java:26]: Okay, I added some strings. Let me know what you think

File: src/main/java/com/transloadit/sdk/TusUploadRunnable.java (hunk 9 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/TusUploadRunnable.java:106]: It basically cheeks whether the upload has been started already or not. Because the pausing behavior is different then. I will rename it to `uploadHasBeenStarted `  to make it more clear

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java (hunk 3 above)
Comment (cdr-chakotay) [reply examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:126]: Done

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java (hunk 4 above)
Comment (cdr-chakotay) [reply examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:140]: Yes and no, I added it back to uncommented as it might be a good Idea to show it.

File: src/main/java/com/transloadit/sdk/async/UploadProgressListener.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/async/UploadProgressListener.java:46]: Also, Async Assembly had similar statuses and I wanted to preserve a fully working alternative

File: src/main/java/com/transloadit/sdk/Assembly.java (hunk 7 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/Assembly.java:214]: I thought it is a better fitting name, but I can change it back. :) Anyway, this release is a Major version. Isn't it?

Let me know, what you prefer.

File: .github/linters/sun_checks.xml (hunk 13 above)
[the remark this answers is not in the document]
Comment (Acconut) [reply .github/linters/sun_checks.xml:140]: Ok, if it causes to much hassle, let's remove it

File: examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java (hunk 5 above)
Comment (Acconut) [reply examples/src/main/java/com/transloadit/examples/MultiStepProcessing.java:167]: Then let's remove the comment :)

File: src/main/java/com/transloadit/sdk/async/UploadProgressListener.java (hunk 12 above)
[the remark this answers is not in the document]
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/async/UploadProgressListener.java:46]: Will merge the Listeners into one as arranged

File: src/main/java/com/transloadit/sdk/TusUploadRunnable.java (hunk 9 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/TusUploadRunnable.java]: Will add commentary

File: src/main/java/com/transloadit/sdk/Assembly.java (hunk 8 above)
Comment (cdr-chakotay) [reply src/main/java/com/transloadit/sdk/Assembly.java:417]: Okay now it is only used for the upload progress Event. Is that okay? Or do we not want a progress indicator for the upload and the upload finished event from the socket is sufficient ?

**Comment by Acconut** [comment]
Are you waiting on another review from me side here? I am not sure what the state of this PR is ATM.

**Comment by cdr-chakotay** [comment]
> Are you waiting on another review from me side here? I am not sure what the state of this PR is ATM.

Yes, I do :D, and maybe you could try out production on your end as well. I would not like to deliver it with unseen major bugs I didn't recognize

File: src/main/java/com/transloadit/sdk/Assembly.java (hunk 8 above)
Comment (Acconut) [reply src/main/java/com/transloadit/sdk/Assembly.java:416]: > Okay now it is only used for the upload progress Event. Is that okay?

I think that is sufficient for now.

**Review by Acconut — APPROVED** [review]
Looks good! Amazing work, Florian! Let's merge and ship it :ship:

**Comment by Acconut** [comment]
Let's celebrate the merge :tada:
